"""Refresh the bundled central Krakow offline pack from public primary data.

Run manually: python scripts/refresh-map.py
Exactly one bounded Overpass request; no standard raster tiles are downloaded.
Requires Python 3 standard library only. Generated artifacts are JSON and ArkTS.
"""
from __future__ import annotations

import csv
from datetime import datetime, timezone
import hashlib
import io
import json
import math
from pathlib import Path
import tempfile
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
BOUNDS = {"south": 50.04, "west": 19.915, "north": 50.08, "east": 19.97}
CENTER = (50.06143, 19.93658)
PSP_METADATA = "https://api.dane.gov.pl/1.4/resources/1393918"
PSP_DATASET = "https://api.dane.gov.pl/1.4/datasets/28058"
PSP_DOWNLOAD = "https://api.dane.gov.pl/resources/1393918,punkty-schronienia-dane-csv/file"
OVERPASS = "https://overpass-api.de/api/interpreter"
HEADERS = {"User-Agent": "SafeMesh-HackYeah2026-OfflinePack/0.1 (manual bounded research extract)",
           "Accept": "application/json,text/csv,*/*"}


def fetch(url: str, body: bytes | None = None) -> bytes:
    req = urllib.request.Request(url, data=body, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=120) as response:
        return response.read()


def km(lat: float, lon: float) -> float:
    a1, a2 = math.radians(CENTER[0]), math.radians(lat)
    dlat, dlon = a2 - a1, math.radians(lon - CENTER[1])
    value = math.sin(dlat / 2) ** 2 + math.cos(a1) * math.cos(a2) * math.sin(dlon / 2) ** 2
    return 6371 * 2 * math.atan2(math.sqrt(value), math.sqrt(1 - value))


def simplify(points: list[list[float]], tolerance: float = 0.000035) -> list[list[float]]:
    """Douglas-Peucker, latitude-normalized; about 4 m at this latitude."""
    if len(points) <= 2:
        return points
    a, b = points[0], points[-1]
    vx, vy = (b[1] - a[1]) * 0.642, b[0] - a[0]
    vv = vx * vx + vy * vy
    max_distance, index = -1.0, 0
    for i, point in enumerate(points[1:-1], start=1):
        px, py = (point[1] - a[1]) * 0.642, point[0] - a[0]
        t = max(0.0, min(1.0, (px * vx + py * vy) / vv)) if vv else 0.0
        distance = math.hypot(px - t * vx, py - t * vy)
        if distance > max_distance:
            max_distance, index = distance, i
    if max_distance <= tolerance:
        return [a, b]
    return simplify(points[:index + 1], tolerance)[:-1] + simplify(points[index:], tolerance)


def model_source(pack: dict, pack_size: int) -> str:
    q = lambda value: json.dumps(value, ensure_ascii=False)
    lines = [
        "// Generated by scripts/refresh-map.py. Keep data attribution visible in the UI.",
        "// Coordinates are an offline overview; this is not an evacuation-routing graph.",
        "export class GeoPoint {",
        "  lat: number; lon: number;",
        "  constructor(lat: number, lon: number) { this.lat = lat; this.lon = lon; }",
        "}",
        "export class MapBounds {",
        "  south: number; west: number; north: number; east: number;",
        "  constructor(south: number, west: number, north: number, east: number) {",
        "    this.south = south; this.west = west; this.north = north; this.east = east;",
        "  }",
        "}",
        "export class MapLine {",
        "  id: string; name: string; kind: string; points: GeoPoint[];",
        "  constructor(id: string, name: string, kind: string, points: GeoPoint[]) {",
        "    this.id = id; this.name = name; this.kind = kind; this.points = points;",
        "  }",
        "}",
        "export class SafePoint {",
        "  id: string; name: string; address: string; lat: number; lon: number;",
        "  type: string; availability: string; description: string; source: string; sourceDate: string;",
        "  constructor(id: string, name: string, address: string, lat: number, lon: number,",
        "    type: string, availability: string, description: string, source: string, sourceDate: string) {",
        "    this.id = id; this.name = name; this.address = address; this.lat = lat; this.lon = lon;",
        "    this.type = type; this.availability = availability; this.description = description;",
        "    this.source = source; this.sourceDate = sourceDate;",
        "  }",
        "}",
        "export const MAP_BOUNDS: MapBounds = new MapBounds(50.04, 19.915, 50.08, 19.97);",
        f"export const MAP_CENTER: GeoPoint = new GeoPoint({CENTER[0]}, {CENTER[1]});",
        f"export const MAP_SOURCE_DATE: string = {q(pack['metadata']['pspDataDate'])};",
        f"export const MAP_OSM_DATE: string = {q(pack['metadata']['osmDataDate'])};",
        f"export const MAP_PACK_LABEL: string = {q('Kraków • centrum')};",
        f"export const MAP_PACK_BYTES: number = {pack_size};",
        f"export const MAP_ATTRIBUTION: string = {q('© OpenStreetMap contributors (ODbL) • KG PSP (CC BY 4.0)')};",
        f"export const MAP_NOTICE: string = {q('Punkty schronienia z bazy PSP. Dostępność według źródła, bez potwierdzenia na żywo. Wybrany wycinek, niepełna lista. Brak wyznaczania bezpiecznej trasy.')};",
    ]
    for export, key in (("MAP_STREETS", "streets"), ("MAP_AREAS", "areas"), ("MAP_RIVERS", "rivers")):
        # Keep each initializer bounded, avoiding a giant bytecode function.
        chunks = [pack[key][i:i + 120] for i in range(0, len(pack[key]), 120)]
        for index, chunk in enumerate(chunks):
            lines.append(f"function {export.lower()}_{index}(): MapLine[] {{ return [")
            for feature in chunk:
                points = ",".join(f"new GeoPoint({p[0]},{p[1]})" for p in feature["points"])
                lines.append(f"  new MapLine({q(feature['id'])},{q(feature['name'])},{q(feature['kind'])},[{points}]),")
            lines.append("]; }")
        if chunks:
            expr = f"{export.lower()}_0()"
            for index in range(1, len(chunks)):
                expr += f".concat({export.lower()}_{index}())"
            lines.append(f"export const {export}: MapLine[] = {expr};")
        else:
            lines.append(f"export const {export}: MapLine[] = [];")
    lines.append("export const SAFE_POINTS: SafePoint[] = [")
    for point in pack["safePoints"]:
        values = [point[key] for key in ("id", "name", "address", "lat", "lon", "type", "availability", "description", "source", "sourceDate")]
        lines.append("  new SafePoint(" + ",".join(q(value) for value in values) + "),")
    lines.append("];\n")
    return "\n".join(lines)


def main() -> None:
    print("Reading official PSP metadata and CSV...", flush=True)
    metadata = json.loads(fetch(PSP_METADATA))["data"]["attributes"]
    dataset = json.loads(fetch(PSP_DATASET))["data"]["attributes"]
    if dataset["license_name"] != "CC BY 4.0":
        raise RuntimeError("Source licence changed; review before redistributing.")
    cache_dir = Path(tempfile.gettempdir()) / "safemesh-map-sources"
    cache_dir.mkdir(parents=True, exist_ok=True)
    csv_cache = cache_dir / ("psp-" + metadata["data_date"] + ".csv")
    csv_bytes = csv_cache.read_bytes() if csv_cache.exists() else fetch(PSP_DOWNLOAD)
    if not csv_cache.exists():
        csv_cache.write_bytes(csv_bytes)
    reader = csv.DictReader(io.StringIO(csv_bytes.decode("utf-8-sig"), newline=""))
    points = []
    matching = 0
    for row in reader:
        if row["Gmina"] != "Kraków":
            continue
        lat, lon = float(row["Szerokosc geograficzna"]), float(row["Dlugosc geograficzna"])
        if not (BOUNDS["south"] <= lat <= BOUNDS["north"] and BOUNDS["west"] <= lon <= BOUNDS["east"]):
            continue
        matching += 1
        points.append({"id": row["Identyfikator publiczny"], "name": row["Nazwa"], "address": row["Adres"],
                       "lat": round(lat, 7), "lon": round(lon, 7), "type": row["Rodzaj obiektu"],
                       "availability": row["Dostepnosc"], "description": row["Opis ogolny"],
                       "source": "Komenda Główna Państwowej Straży Pożarnej", "sourceDate": metadata["data_date"]})
    points.sort(key=lambda point: (km(point["lat"], point["lon"]), point["id"]))
    points = points[:40]
    if len(points) < 20:
        raise RuntimeError(f"Only {len(points)} central Krakow source points; review filter.")
    print(f"Selected {len(points)} closest source records from {matching} within bounds.", flush=True)
    bbox = f"({BOUNDS['south']},{BOUNDS['west']},{BOUNDS['north']},{BOUNDS['east']})"
    query = ('[out:json][timeout:25];('
             f'way[highway~"^(primary|secondary|tertiary|residential|pedestrian|living_street|unclassified)$"]{bbox};'
             f'way[natural=water]{bbox};way[leisure=park]{bbox};way[waterway=river]{bbox};'
             ');out geom;')
    print("One bounded Overpass vector query (no raster tiles)...", flush=True)
    raw_osm = fetch(OVERPASS + "?" + urllib.parse.urlencode({"data": query}))
    osm = json.loads(raw_osm)
    if "remark" in osm:
        raise RuntimeError("Overpass returned a warning/error: " + osm["remark"])
    streets, areas, rivers = [], [], []
    for element in osm["elements"]:
        tags = element.get("tags", {})
        geometry = [[round(p["lat"], 6), round(p["lon"], 6)] for p in element.get("geometry", [])]
        if len(geometry) < 2:
            continue
        geometry = simplify(geometry)
        kind = tags.get("highway", "river" if tags.get("waterway") == "river" else "water" if tags.get("natural") == "water" else "park")
        feature = {"id": f"way/{element['id']}", "name": tags.get("name", ""), "kind": kind, "points": geometry}
        if "highway" in tags:
            streets.append(feature)
        elif kind == "river":
            rivers.append(feature)
        elif len(geometry) >= 4 and geometry[0] == geometry[-1]:
            areas.append(feature)
    pack = {"schemaVersion": 1, "bounds": BOUNDS, "center": {"lat": CENTER[0], "lon": CENTER[1]},
            "metadata": {"label": "Kraków • centrum", "generatedAt": datetime.now(timezone.utc).isoformat(),
                         "pspDataDate": metadata["data_date"], "pspSource": PSP_DOWNLOAD, "pspMetadata": PSP_METADATA,
                         "pspLicense": "CC BY 4.0", "pspPublisher": "Komenda Główna Państwowej Straży Pożarnej",
                         "pspSourceSha256": hashlib.sha256(csv_bytes).hexdigest(), "pspAvailableInBounds": matching,
                         "selection": "40 source records closest to Rynek Główny inside the bounded map; not comprehensive",
                         "osmDataDate": osm["osm3s"]["timestamp_osm_base"], "osmSource": OVERPASS,
                         "osmQuery": query, "osmLicense": "ODbL 1.0", "osmAttribution": "© OpenStreetMap contributors",
                         "osmSourceSha256": hashlib.sha256(raw_osm).hexdigest(), "geometrySimplificationMetersApprox": 4,
                         "notice": "Temporary protective points, not certified bomb shelters. Availability is source-reported, not live. No evacuation routing."},
            "streets": streets, "areas": areas, "rivers": rivers, "safePoints": points}
    payload = json.dumps(pack, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    if len(payload) > 1500000:
        raise RuntimeError(f"Pack unexpectedly large: {len(payload)} bytes; narrow query.")
    raw_path = ROOT / "entry/src/main/resources/rawfile/map-pack.json"
    model_path = ROOT / "entry/src/main/ets/model/OfflineMapData.ets"
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    model_path.parent.mkdir(parents=True, exist_ok=True)
    raw_path.write_bytes(payload)
    model_path.write_text(model_source(pack, len(payload)), encoding="utf-8")
    print(json.dumps({"jsonBytes": len(payload), "arktsBytes": model_path.stat().st_size,
                      "streets": len(streets), "areas": len(areas), "rivers": len(rivers),
                      "safePoints": len(points), "pspDate": metadata["data_date"]}, indent=2))


if __name__ == "__main__":
    main()
